name: Build and publish to GitHub Packages
on:
  push:
    branches:
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
      
      - name: Add .npmrc file
        run: |
          echo "@tiptap-pro:registry=https://registry.tiptap.dev/" > .npmrc
          echo "//registry.tiptap.dev/:_authToken=${{ secrets.TIPTAP_AUTH_TOKEN }}" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.PUBLISH_GITHUB_PACKAGES }}" >> .npmrc
      
      - name: Install Dependencies
        run: npm i
      
      - name: Build Package
        run: npm run pr-build
      
      - name: Publish Package
        run: npm publish
